[build]
  # Command to build your project with Vite
  command = "npm run build"

  # Directory with the built files
  publish = "dist"

[[redirects]]
  # Redirects all requests to /index.html (React Router's entry point)
  from = "/*"
  to = "/index.html"
  status = 200